name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Build & Deploy Backend to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: dashboardambiental
          install_components: 'beta'

      - name: Build and push Docker image (Backend)
        run: |
          gcloud builds submit ./backend \
            --tag gcr.io/dashboardambiental/backend:latest

      - name: Deploy to Cloud Run (Backend)
        run: |
          gcloud run deploy backend \
            --image gcr.io/dashboardambiental/backend:latest \
            --region northamerica-south1 \
            --platform managed \
            --allow-unauthenticated

  deploy-frontend:
    name: Build & Deploy Frontend to Cloud Run
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: dashboardambiental

      - name: Build and push Docker image (Frontend)
        run: |
          gcloud builds submit ./frontend \
            --tag gcr.io/dashboardambiental/frontend:latest

      - name: Deploy to Cloud Run (Frontend)
        run: |
          gcloud run deploy frontend \
            --image gcr.io/dashboardambiental/frontend:latest \
            --region northamerica-south1 \
            --platform managed \
            --allow-unauthenticated
